"""
将训练好的 SB3 模型导出为 C 头文件, 可直接包含到 STM32 固件中.

输出: firmware/rl_model.h
  - 权重数组 (float32 或 int8 量化)
  - rl_predict() 函数: 纯 C 实现的 MLP 前向传播

用法:
  uv run src/deploy/export_to_c.py                                      # 默认模型
  uv run src/deploy/export_to_c.py --model data/models/balance_sac_final.zip
  uv run src/deploy/export_to_c.py --quantize int8                      # int8 量化 (更小更快)

要求: 模型必须是 MLP (MlpPolicy), 支持任意层数和宽度.

部署到 STM32 步骤:
  1. 训练小网络: uv run src/train/train.py --net-arch 64 64 --timesteps 300000
  2. 导出: uv run src/deploy/export_to_c.py
  3. 把生成的 firmware/rl_model.h 复制到 Keil 工程
  4. 在 control.c 的 Control_mode==1 分支替换 LQR 为 rl_predict()
"""

import argparse
import sys
from pathlib import Path

import numpy as np
from stable_baselines3 import SAC, PPO, TD3

sys.path.insert(0, str(Path(__file__).resolve().parent.parent.parent))

REPO_ROOT = Path(__file__).resolve().parent.parent.parent
ALGO_MAP = {"SAC": SAC, "PPO": PPO, "TD3": TD3}


def extract_mlp_weights(model):
    """从 SB3 模型提取 actor MLP 的 (weight, bias) 列表."""
    if hasattr(model, "actor"):
        # SAC / TD3: actor.mu (deterministic action head)
        actor = model.actor
        if hasattr(actor, "mu"):
            mu = actor.mu
        else:
            mu = None
        latent = actor.latent_pi
    else:
        # PPO: policy network
        actor = model.policy
        latent = actor.mlp_extractor.policy_net
        mu = actor.action_net

    layers = []
    for module in latent.modules():
        if hasattr(module, "weight") and hasattr(module, "bias"):
            w = module.weight.detach().cpu().numpy()
            b = module.bias.detach().cpu().numpy()
            layers.append((w, b, "relu"))

    if mu is not None:
        for module in mu.modules():
            if hasattr(module, "weight") and hasattr(module, "bias"):
                w = module.weight.detach().cpu().numpy()
                b = module.bias.detach().cpu().numpy()
                layers.append((w, b, "tanh"))
                break

    return layers


def generate_c_header(layers, quantize="float32", u_max=200.0):
    """生成 C 头文件字符串."""
    lines = []
    lines.append("/* Auto-generated by export_to_c.py — DO NOT EDIT */")
    lines.append("#ifndef RL_MODEL_H")
    lines.append("#define RL_MODEL_H")
    lines.append("")
    lines.append("#include <math.h>")
    lines.append("")

    total_params = sum(w.size + b.size for w, b, _ in layers)
    total_bytes = total_params * (1 if quantize == "int8" else 4)
    lines.append(
        f"/* Model: {len(layers)} layers, {total_params} params, {total_bytes} bytes ({quantize}) */"
    )
    lines.append(f"/* Action scale: output is tanh * {u_max} */")
    lines.append("")

    if quantize == "int8":
        lines.append(
            "/* Quantization: weights stored as int8, scale factors per layer */"
        )
        lines.append("")

    for i, (w, b, act) in enumerate(layers):
        out_dim, in_dim = w.shape
        if quantize == "int8":
            w_scale = np.abs(w).max() / 127.0 if np.abs(w).max() > 0 else 1.0
            b_scale = np.abs(b).max() / 127.0 if np.abs(b).max() > 0 else 1.0
            w_q = np.clip(np.round(w / w_scale), -127, 127).astype(np.int8)
            b_q = np.clip(np.round(b / b_scale), -127, 127).astype(np.int8)
            lines.append(f"static const float W{i}_scale = {w_scale:.8e}f;")
            lines.append(f"static const float B{i}_scale = {b_scale:.8e}f;")
            lines.append(f"static const signed char W{i}[{out_dim}][{in_dim}] = {{")
            for row in w_q:
                lines.append("  {" + ",".join(str(x) for x in row) + "},")
            lines.append("};")
            lines.append(f"static const signed char B{i}[{out_dim}] = {{")
            lines.append("  " + ",".join(str(x) for x in b_q))
            lines.append("};")
        else:
            lines.append(f"static const float W{i}[{out_dim}][{in_dim}] = {{")
            for row in w:
                lines.append("  {" + ",".join(f"{x:.7e}f" for x in row) + "},")
            lines.append("};")
            lines.append(f"static const float B{i}[{out_dim}] = {{")
            lines.append("  " + ",".join(f"{x:.7e}f" for x in b) + "")
            lines.append("};")
        lines.append("")

    # Generate inference function
    max_dim = max(max(w.shape[0], w.shape[1]) for w, _, _ in layers)
    lines.append(f"static float _buf0[{max_dim}];")
    lines.append(f"static float _buf1[{max_dim}];")
    lines.append("")
    lines.append("/* Forward pass: state[8] -> action[2] */")
    lines.append("static void rl_predict(const float state[8], float action[2]) {")
    lines.append(f"  float *in = _buf0, *out = _buf1, *tmp;")
    lines.append(f"  int i, j;")
    lines.append(f"  for (i = 0; i < 8; i++) in[i] = state[i];")
    lines.append("")

    for i, (w, b, act) in enumerate(layers):
        out_dim, in_dim = w.shape
        lines.append(f"  /* Layer {i}: {in_dim} -> {out_dim}, {act} */")
        lines.append(f"  for (i = 0; i < {out_dim}; i++) {{")
        if quantize == "int8":
            lines.append(f"    float sum = B{i}[i] * B{i}_scale;")
            lines.append(
                f"    for (j = 0; j < {in_dim}; j++) sum += W{i}[i][j] * W{i}_scale * in[j];"
            )
        else:
            lines.append(f"    float sum = B{i}[i];")
            lines.append(
                f"    for (j = 0; j < {in_dim}; j++) sum += W{i}[i][j] * in[j];"
            )
        if act == "relu":
            lines.append(f"    out[i] = sum > 0.0f ? sum : 0.0f;")
        elif act == "tanh":
            lines.append(f"    out[i] = tanhf(sum);")
        else:
            lines.append(f"    out[i] = sum;")
        lines.append(f"  }}")
        lines.append(f"  tmp = in; in = out; out = tmp;")
        lines.append("")

    lines.append(f"  /* Scale tanh output to action range */")
    lines.append(f"  action[0] = in[0] * {u_max:.1f}f;")
    lines.append(f"  action[1] = in[1] * {u_max:.1f}f;")
    lines.append("}")
    lines.append("")
    lines.append("#endif /* RL_MODEL_H */")
    lines.append("")

    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--algo", default="SAC", choices=list(ALGO_MAP))
    parser.add_argument("--model", default=None)
    parser.add_argument("--quantize", default="float32", choices=["float32", "int8"])
    parser.add_argument("--output", default=str(REPO_ROOT / "firmware" / "rl_model.h"))
    parser.add_argument(
        "--u-max", type=float, default=200.0, help="Action scale (training U_MAX)"
    )
    args = parser.parse_args()

    model_path = args.model or str(
        REPO_ROOT / "data" / "models" / f"balance_{args.algo.lower()}_final.zip"
    )
    print(f"Loading model from {model_path} ...")
    model = ALGO_MAP[args.algo].load(model_path, device="cpu")

    print("Extracting MLP weights ...")
    layers = extract_mlp_weights(model)

    for i, (w, b, act) in enumerate(layers):
        print(f"  Layer {i}: {w.shape[1]} -> {w.shape[0]} ({act})")

    total_params = sum(w.size + b.size for w, b, _ in layers)
    size_f32 = total_params * 4
    size_i8 = total_params * 1
    print(
        f"  Total: {total_params} params = {size_f32 / 1024:.1f} KB (float32) / {size_i8 / 1024:.1f} KB (int8)"
    )

    if size_f32 > 200_000 and args.quantize == "float32":
        print(f"\n[WARN] float32 model > 200KB, may exceed STM32 ROM!")
        print(f"       Consider: --quantize int8, or train with --net-arch 64 64")

    header = generate_c_header(layers, quantize=args.quantize, u_max=args.u_max)

    out_path = Path(args.output)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(header)
    print(f"\nExported to {out_path}")
    print(f"  Quantization: {args.quantize}")
    actual_size = out_path.stat().st_size
    print(f"  File size: {actual_size / 1024:.1f} KB")

    print(f"\n=== 部署到 STM32 ===")
    print(f"1. 将 {out_path.name} 复制到 Keil 工程的 MiniBalance/ 目录")
    print(f'2. 在 control.c 顶部 #include "rl_model.h"')
    print(f"3. 替换 Control_mode==1 分支:")
    print(f"     float state[8] = {{theta_L, theta_R, theta_1, theta_2,")
    print(
        f"                        theta_L_dot, theta_R_dot, theta_dot_1, theta_dot_2}};"
    )
    print(f"     float action[2];")
    print(f"     rl_predict(state, action);")
    print(f"     u_L = action[0];")
    print(f"     u_R = action[1];")


if __name__ == "__main__":
    main()
